version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.2-stretch-browsers
        working_directory: ~/csci39549-calculator
	steps:
            - checkout
            - run: 
	       name: Install requirements
	       command: |
                 pip install --user -r requirements.txt
